# Site settings
name: That Bynln
title: ThatBynln | Personal Page For Public
description: Still Learning New Stuff, FOSS Supporter & Cyber Enthusiast With A Diff- Vision.
url: https://thatbynln.github.io/
baseurl: ''
email: hi@thatbynln.slmail.me
cover: https://thatbynln.github.io/img/og.png
logo: https://thatbynln.github.io/img/emojis/technologist.png
resume: https://thatbynln.github.io/resume.pdf
social:
  - title: email
    url: mailto:hi@thatbynln.slmail.me
  - title: twitter
    url: https://twitter.com/thatbynln
  - title: instagram
    url: https://instagram.com/beyondlon
  - title: github
    url: https://github.com/thatbynln
 
# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
